INSERT INTO SP_INQUIRY_HISTORY
SELECT B.*
FROM SP_INQUIRY@ORASERVICE A
JOIN SP_INQUIRY_HISTORY@ORASERVICE B ON A.INQ_NO = B.INQ_NO AND A.INQ_REV = B.INQ_REV
WHERE INQ_DATE >= TO_DATE('2023-01-01' , 'YYYY-MM-DD')
;

UPDATE SP_INQUIRY_HISTORY SET inqh_action = 46 WHERE INQH_ACTION = 	17;
UPDATE SP_INQUIRY_HISTORY SET inqh_action = 45 WHERE INQH_ACTION = 	18;
UPDATE SP_INQUIRY_HISTORY SET inqh_action = 44 WHERE INQH_ACTION = 	16;
UPDATE SP_INQUIRY_HISTORY SET inqh_action = 43 WHERE INQH_ACTION = 	15;
UPDATE SP_INQUIRY_HISTORY SET inqh_action = 41 WHERE INQH_ACTION = 	14;
UPDATE SP_INQUIRY_HISTORY SET inqh_action = 40 WHERE INQH_ACTION = 	13;
UPDATE SP_INQUIRY_HISTORY SET inqh_action = 30 WHERE INQH_ACTION = 	20;
UPDATE SP_INQUIRY_HISTORY SET inqh_action = 27 WHERE INQH_ACTION = 	10;
UPDATE SP_INQUIRY_HISTORY SET inqh_action = 26 WHERE INQH_ACTION = 	9;
UPDATE SP_INQUIRY_HISTORY SET inqh_action = 22 WHERE INQH_ACTION = 	5;
UPDATE SP_INQUIRY_HISTORY SET inqh_action = 21 WHERE INQH_ACTION = 	4;
UPDATE SP_INQUIRY_HISTORY SET inqh_action = 4	 WHERE INQH_ACTION = 24;
UPDATE SP_INQUIRY_HISTORY SET inqh_action = 24 WHERE INQH_ACTION = 	7;
COMMIT;

DELETE FROM SP_INQUIRY_HISTORY@ORASERVICE  t
WHERE ROWID  NOT IN  (
    SELECT MIN(ROWID)
    FROM SP_INQUIRY_HISTORY@ORASERVICE
    --WHERE  INQ_NO = 'INMX-25569'
    GROUP BY INQ_NO, INQ_REV, INQH_USER, INQH_ACTION, INQH_LATEST, INQH_DATE, INQH_REMARK
) ;
--AND INQ_NO = 'INMX-25569'
--ORDER BY INQH_DATE;