INSERT INTO SP_INQUIRY_DETAIL ( INQG_GROUP, INQD_SEQ, INQD_RUNNO, INQD_MFGORDER, INQD_ITEM, INQD_CAR, INQD_PARTNAME, INQD_DRAWING, INQD_VARIABLE, INQD_QTY
    , INQD_UM, INQD_SUPPLIER, INQD_SENDPART, INQD_UNREPLY, INQD_FC_COST, INQD_TC_COST, INQD_UNIT_PRICE, INQD_FC_BASE, INQD_TC_BASE, INQD_MAR_REMARK
    , INQD_DES_REMARK, INQD_FIN_REMARK, INQD_LATEST, INQD_OWNER, CREATE_AT, CREATE_BY, UPDATE_AT, UPDATE_BY, INQD_COMPARE, INQD_COMPARE_DATE, INQD_OWNER_GROUP
    , ITEMID, INQID, TEST_FLAG, TEST_MESSAGE, AUTO_ADD, INQD_PREV, UPDATE_CODE, INQD_EXRATE)
SELECT C.INQG_ID, INQD_SEQ, INQD_RUNNO, INQD_MFGORDER, INQD_ITEM, INQD_CAR, INQD_PARTNAME, INQD_DRAWING, INQD_VARIABLE, INQD_QTY, INQD_UM
    , INQD_SUPPLIER, INQD_SENDPART, INQD_UNREPLY, INQD_FC_COST, INQD_TC_COST, INQD_UNIT_PRICE, INQD_FC_BASE, INQD_TC_BASE, INQD_MAR_REMARK
    , INQD_DES_REMARK, INQD_FIN_REMARK, INQD_LATEST, INQD_OWNER, A.CREATE_AT, A.CREATE_BY, A.UPDATE_AT, A.UPDATE_BY, INQD_COMPARE, INQD_COMPARE_DATE
    , INQD_OWNER_GROUP, ITEMID, B.INQ_ID, TEST_FLAG, TEST_MESSAGE, AUTO_ADD, INQD_PREV, UPDATE_CODE, INQD_EXRATE
FROM SP_INQUIRY_DETAIL@ORASERVICE A
JOIN SP_INQUIRY B ON A.INQID = B.TEMPCOLS
JOIN SP_INQUIRY_GROUP C ON C.INQ_ID = B.INQ_ID AND FLOOR(INQD_ITEM/100) = C.INQG_GROUP
ORDER BY 1;