INSERT INTO SP_INQUIRY_GROUP (INQ_ID, INQG_GROUP, INQG_REV, INQG_ASG, INQG_DES, INQG_CHK, INQG_CLASS, INQG_ASG_DATE, INQG_DES_DATE, INQG_CHK_DATE, INQG_DES_REASON, INQG_STATUS, INQG_LATEST, IS_MAIL)
SELECT B.INQ_ID, INQG_GROUP, INQG_REV, INQG_ASG, INQG_DES, INQG_CHK, INQG_CLASS, INQG_ASG_DATE, INQG_DES_DATE, INQG_CHK_DATE, INQG_DES_REASON, INQG_STATUS, INQG_LATEST, IS_MAIL
FROM SP_INQUIRY_GROUP@ORASERVICE A
JOIN SP_INQUIRY B ON A.INQ_ID = B.TEMPCOLS;
COMMIT;