INSERT INTO SP_INQUIRY_TIMELINE (INQ_NO, INQ_REV, MAR_USER, MAR_SEND, DE_READ, DE_CONFIRM, BM_COFIRM, PKC_USER, PKC_READ, PKC_CONFIRM,
FIN_USER, FIN_READ, FIN_CONFIRM, FCK_USER, FCK_READ, FCK_CONFIRM, FMN_USER, FMN_READ, FMN_CONFIRM, QT_USER, QT_READ, QT_CONFIRM)
SELECT  INQ_NO, INQ_REV, INQ_MAR_PIC MAR_USER, INQ_MAR_SENT MAR_SEND
, INQ_MRE_RECV DE_READ, INQ_MRE_FINISH DE_CONFIRM, INQ_BM_DATE BM_COFIRM
, INQ_PKC_PIC PKC_USER, CASE WHEN INQ_PKC_REQ = 1 THEN INQ_MRE_FINISH ELSE NULL END PKC_READ, CASE WHEN INQ_PKC_REQ = 1 THEN INQ_PKC_FINISH ELSE NULL END PKC_CONFIRM
, INQ_FIN_PIC FIN_USER, INQ_FIN_RECV FIN_READ, INQ_FIN_CONFIRM FIN_CONFIRM
, INQ_FIN_CHK FCK_USER, INQ_FIN_CONFIRM FCK_READ, INQ_FIN_CHECKED FCK_CONFIRM
, INQ_FIN_CHK FMN_USER, INQ_FIN_CHECKED FMN_READ, INQ_FIN_FINISH FMN_CONFIRM
, QUO_PIC QT_USER, INQ_FIN_FINISH QT_READ, INQ_FINISH QT_CONFIRM
FROM SP_INQUIRY@ORASERVICE A
LEFT JOIN SP_QUOTATION@ORASERVICE B ON A.INQ_ID = B.QUO_INQ
WHERE INQ_DATE >= TO_DATE('2023-01-01' , 'YYYY-MM-DD')
;