INSERT INTO SP_INQUIRY (
    INQ_NO, INQ_REV, INQ_STATUS, INQ_DATE, INQ_TRADER, INQ_AGENT, INQ_COUNTRY, INQ_TYPE, INQ_PRJNO, INQ_PRJNAME, INQ_SHOPORDER
    , INQ_SERIES, INQ_OPERATION, INQ_SPEC, INQ_PRDSCH, INQ_QUOTATION_TYPE, INQ_DELIVERY_TERM, INQ_DELIVERY_METHOD, INQ_SHIPMENT
    , INQ_MAR_PIC, CREATE_AT, UPDATE_AT, CREATE_BY, UPDATE_BY, INQ_LATEST, TOTAL_FC, TOTAL_TC, GRAND_TOTAL, TOTAL_UNIT_PRICE
    , INQ_PKC_REQ, INQ_EXTEND, INQ_CUR, INQ_ACTUAL_PO, INQ_CUSTRQS, INQ_CUSTOMER, INQ_CONTRACTOR, INQ_ENDUSER, INQ_PORT, INQ_USERPART
    , INQ_TCCUR, TEMPCOLS
)
SELECT INQ_NO, INQ_REV, INQ_STATUS, INQ_DATE, INQ_TRADER, INQ_AGENT, INQ_COUNTRY, INQ_TYPE, INQ_PRJNO, INQ_PRJNAME, INQ_SHOPORDER
    , INQ_SERIES, INQ_OPERATION, INQ_SPEC, INQ_PRDSCH, INQ_QUOTATION_TYPE, INQ_DELIVERY_TERM, INQ_DELIVERY_METHOD, INQ_SHIPMENT
    , INQ_MAR_PIC, CREATE_AT, UPDATE_AT, CREATE_BY, UPDATE_BY, INQ_LATEST, TOTAL_FC, TOTAL_TC, GRAND_TOTAL, TOTAL_UNIT_PRICE
    , INQ_PKC_REQ, INQ_EXTEND, INQ_CUR, INQ_ACTUAL_PO, INQ_CUSTRQS, INQ_CUSTOMER, INQ_CONTRACTOR, INQ_ENDUSER, INQ_PORT, INQ_USERPART
    , INQ_TCCUR, INQ_ID
FROM SP_INQUIRY@ORASERVICE
WHERE INQ_DATE >= TO_DATE('2023-01-01', 'YYYY-MM-DD');
COMMIT;