Insert into SP_SHIPMENT (SHIPMENT_ID,SHIPMENT_VALUE,SHIPMENT_DESC,SHIPMENT_STATUS) values (1,90,'90 Days after receiving P/O',1);
Insert into SP_SHIPMENT (SHIPMENT_ID,SHIPMENT_VALUE,SHIPMENT_DESC,SHIPMENT_STATUS) values (2,120,'120 Days after receiving P/O',1);
Insert into SP_SHIPMENT (SHIPMENT_ID,SHIPMENT_VALUE,SHIPMENT_DESC,SHIPMENT_STATUS) values (3,150,'150 Days after receiving P/O',1);
Insert into SP_SHIPMENT (SHIPMENT_ID,SHIPMENT_VALUE,SHIPMENT_DESC,SHIPMENT_STATUS) values (4,180,'180 Days after receiving P/O',1);
Insert into SP_SHIPMENT (SHIPMENT_ID,SHIPMENT_VALUE,SHIPMENT_DESC,SHIPMENT_STATUS) values (5,60,'60 Days after receiving P/O',1);
