  CREATE TABLE SP_ATTACHED 
   (	INQ_NO VARCHAR(50 ) PRIMARY KEY, 
	FILE_NAME VARCHAR(100 ) , 
	FILE_ORIGINAL_NAME VARCHAR(150 ) , 
	FILE_SIZE INT,
	FILE_TYPE VARCHAR(10 ) , 
	FILE_CLASS VARCHAR(50 ), 
	FILE_STATUS INT,
	FILE_OWNER VARCHAR(5), 
	FILE_MAR_READ INT, 
	FILE_DES_READ INT, 
	FILE_CREATE_AT TIMESTAMP (6), 
	FILE_CREATE_BY VARCHAR(100 )
)