 CREATE TABLE SP_CURRENCY 
   (	CURR_YEAR INT , 
	CURR_PERIOD INT , 
	CURR_CODE VARCHAR(3 ) , 
	CURR_RATE INT, 
	CURR_LATEST VARCHAR(1 ), 
	CURR_UPDATE_DATE TIMESTAMP (6), 
	CURR_UPDATE_BY VARCHAR(100 )
	)