CREATE TABLE SP_INQUIRY_CONTROL 
   (	CNT_PREFIX VARCHAR(10 ), 
	CNT_AGENT VARCHAR(3 ), 
	CNT_TRADER VARCHAR(20 ), 
	CNT_QUOTATION INT(2,0), 
	CNT_TERM INT(2,0), 
	CNT_WEIGHT INT(1,0) DEFAULT 0, 
	CNT_METHOD INT(1,0)
   )