CREATE TABLE SP_INQUIRY_GROUP (	
	INQG_ID INT, 
	INQ_ID FLOAT(10,0), 
	INQG_GROUP FLOAT(3,0), 
	INQG_REV VARCHAR(3 ), 
	INQG_ASG VARCHAR(5 ), 
	INQG_DES VARCHAR(5 ), 
	INQG_CHK VARCHAR(5 ), 
	INQG_CLASS VARCHAR(3 ), 
	INQG_ASG_DATE TIMESTAMP (6), 
	INQG_DES_DATE TIMESTAMP (6), 
	INQG_CHK_DATE TIMESTAMP (6), 
	INQG_DES_REASON VARCHAR(250 ), 
	INQG_STATUS FLOAT(2,0), 
	INQG_LATEST FLOAT(1,0), 
	IS_MAIL CHAR(1 )
   ) 