 CREATE TABLE SP_PRICE_RATIO 
   (	ID INT, 
	TRADER VARCHAR(10 ), 
	SUPPLIER VARCHAR(10 ), 
	QUOTATION INT, 
	FORMULA FLOAT(7,3), 
	FREIGHT_SEA FLOAT(7,4), 
	FREIGHT_AIR FLOAT(7,4), 
	FREIGHT_COURIER FLOAT(7,4), 
	UPDATE_BY VARCHAR(100 ), 
	UPDATE_AT VARCHAR(20 ), 
	CURRENCY VARCHAR(3 ), 
	STATUS CHAR(1 )
   )