CREATE TABLE TMAINTAINTYPE (
    ID INT PRIMARY KEY,
	ABBREVIATION VARCHAR(12),
	DETAIL VARCHAR(50),
	EDI_PART_INT VARCHAR(10),
	PC_FORM VARCHAR(5),
	SERIESNAME VARCHAR(50),
	DESCRIPTION_INVOICE VARCHAR(50),
	PREASSY VARCHAR(10),
	CAPAMIN INT,
	CAPAMAX INT,
	SPEDVALUE VARCHAR(200),
	REFERXML VARCHAR(50),
	STATUSACTIVE VARCHAR(5),
	TYPEOFMODEL VARCHAR(50),
	GROUPMAIL VARCHAR(50),
	BYPASSMODEL INT,
	MODERNIZE INT
)